replicaCount: 2

image:
  repository: REPLACE_BY_JENKINS
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: false
  className: nginx
  host: sample.example.com
  path: /